-- Reports System
-- Created: 2026-01-01

CREATE TABLE IF NOT EXISTS reports (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT,
  category ENUM('BUG', 'CONTENT', 'FRAUD', 'SUGGESTION', 'OTHER') NOT NULL,
  subject VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  photo_url VARCHAR(500),
  status ENUM('PENDING', 'IN_PROGRESS', 'RESOLVED', 'CLOSED') DEFAULT 'PENDING',
  admin_notes TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
);
